### ISSUE TITLE
Proposition and request

### ISSUE THREAD

**Issue by phbono** [asjadnaqvi/stata-bimap#1]
Hello,

This is my first time here, apologise if I don't follow the rules.

First the request : I would love to have a 4x4 classification.

The proposition  : just add in syntax declaration  label(passthru) and add `label' in the spmap option. I think it could also be better for polygon to use passthru syntax. Preserve better the macros in arguments.

Thanks for your hard work in stata data viz,

PHB

**Comment by asjadnaqvi** [comment]
Several spmap passthru options added in v1.2.

A 4x4 color ramp in the next update!
