### ISSUE TITLE
add dummy option

### ISSUE THREAD

**Issue by gjiang-economics** [asjadnaqvi/stata-bimap#10]
If one variable is a dummy, how can I set the _cut_ option? I tried _cut(custom)_ with _cutx(0 1)_, but it does not work as expected.

**Comment by asjadnaqvi** [comment]
Currently only 3x3 is supported.

A dummy would require defining a 2x3 or a 3x2 option. Custom bivariate dimensions and their color combinations are likely to come out in the next releases.

**Comment by asjadnaqvi** [comment]
added versions v1.6 and v1.7
