### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by paulhufe** [asjadnaqvi/stata-bimap#12]
Dear Asjad,

I tried to use bimap in its simplest specification to create a map for Germany. However, I encounter problems with the legend --- see attachment 1. 

1) The arrow do not span the entire scale of the interval. This seems to be related to the fact that the value range contains both positive and negative values (see attachement 2 for how it looks if I replace all values by their absolute values).

2) The distance between the colored markets and the axis label is very large. I am not sure what this problem relates to.

Many thanks for all your work. It is truly appreciated.
[test2.pdf](https://github.com/asjadnaqvi/stata-bimap/files/11211719/test2.pdf)
[test1.pdf](https://github.com/asjadnaqvi/stata-bimap/files/11211720/test1.pdf)

Best
Paul

**Comment by asjadnaqvi** [comment]
Dear Paul, 
Another user complained about this an hour ago! I am fixing this now and it should be patched by tonight. 

Best,
Asjad

**Comment by asjadnaqvi** [comment]
Package updated to v1.61. Please install from GitHub and try again:
```
net install bimap, from("https://raw.githubusercontent.com/asjadnaqvi/stata-bimap/main/installation/") replace
```

**Comment by paulhufe** [comment]
Thanks so much. Almost there :) The axis labeling is still off at the endpoints of the value ranges. See the example attached. N.B.: I use the  cutx(numlist), cuty(numlist) options. 
[test3.pdf](https://github.com/asjadnaqvi/stata-bimap/files/11214361/test3.pdf)

Thanks again for your swift turnaround (and sorry for bothering you with the nitty gritty stuff).

**Comment by asjadnaqvi** [comment]
What are the `cutx()` and `cuty()` values?

**Comment by paulhufe** [comment]
cutx(-0.2(0.1)0.5) cuty(-0.2(0.1)0.5)

**Comment by asjadnaqvi** [comment]
Ah that is a bigger issue. `cutx()` and `cuty()` should just be given middle values ranges and not the end points. End points are added automatically and that is what is causing the wierd numbers to show up at the ends. 

I should add a check that if the extreme values are bigger or smaller than the end points then it should throw an error or overwrite them.

**Comment by asjadnaqvi** [comment]
I am closing this thread for the original issue. For the custom cuts, can you open a new thread please!
