### ISSUE TITLE
Axis labeling/Custom cuts

### ISSUE THREAD

**Issue by paulhufe** [asjadnaqvi/stata-bimap#13]
The axis labeling is off at the endpoints of the value ranges when using the custom cut options. See the example attached. 
[test3.pdf](https://github.com/asjadnaqvi/stata-bimap/files/11214361/test3.pdf)

**Comment by paulhufe** [comment]
Dear Asjad, many thanks for the recent updates to bimap. I wondered whether you have plans to address this issue in future iterations of updates. It would be greatly appreciated. Many thanks for your tremendous service to the community :)
Paul

**Comment by asjadnaqvi** [comment]
Can you email me the map layers, data, and scripts please. I will have a look at it.

**Comment by asjadnaqvi** [comment]
Fixed in v1.8
