### ISSUE TITLE
report error --

### ISSUE THREAD

**Issue by arlionn** [asjadnaqvi/stata-bimap#2]
```stata
.    bimap share_hisp share_afam using usa_county_shp_clean, ///
>          cut(pctile) palette(pinkgreen)
function drop() not declared in class ColrSpace
(120 lines skipped)
(error occurred while loading colorpalette.ado)
r(3000);
```

the full version of dofiles is [here](https://github.com/arlionn/stata-bimap/blob/main/dofiles/bimap_dofile.do).

> by Yujun Lian, <arlionn@163.com>

**Comment by asjadnaqvi** [comment]
Try updating the packages:
ado update, update

and check the code again. It is not reading the more recent version of colorpalette.

**Comment by arlionn** [comment]
3x, it is fixed. 













--

------
Lian Yujun
Department of Finance, Sun Yat-Sen University, China, Associate Professor
Tel：86-20-84110648(O) 86-15889968888(M)
***@***.***
Home-Page：http://lingnan.sysu.edu.cn/faculty/lianyujun 

Address: No. 135, Xingang Xi Road, Guangzhou, 510275 (postcode), P. R. China,  Lingnan (University) College, Sun Yat-sen University

-----
 Blogs: https://www.lianxh.cn 




在 2022-05-10 14:51:32，"Asjad Naqvi" ***@***.***> 写道：

Try updating the packages:
ado update, update

and check the code again. It is not reading the more recent version of colorpalette.
