### ISSUE TITLE
Require a North Arrow in the map

### ISSUE THREAD

**Issue by Sadanand-Karun** [asjadnaqvi/stata-bimap#20]
Dear sir, 
Adding direction (i.e., North, South, East, West) is crucial to a map. Though the bivariate maps created using the codes you developed are very good, they lack information on direction. Therefore, I kindly request you to develop code to add a **north arrow** in the bivariate maps as well. It would be of great help. 
Please visit the link: https://www.geographyrealm.com/whats-in-a-map/

https://www.geographyrealm.com/wp-content/uploads/2011/06/parts-of-map-united-states.png

**Comment by asjadnaqvi** [comment]
`arrow()` option is there. Read the helpfile carefully!
