### ISSUE TITLE
If statements and labelling over two lines

### ISSUE THREAD

**Issue by ksaxby** [asjadnaqvi/stata-bimap#8]
Hi there,
First of all - Absolutely LOVE the package!! I tell everyone about it and am using it so much for my PhD papers :D

I was wondering whether it would be possible to have it such that the x-y axis titles could go over two lines? Like in other stata graphing tools you can write title("Outcome title" "title continued") and it would put it over two lines. Or perhaps I am missing something in the help file.
![vic_only](https://user-images.githubusercontent.com/63274020/201587985-42fda4f6-7b3f-4afd-87c0-1cf73d8abd55.png)

The other thing I was wondering is regarding if statements, so if I was wanting to show overall variation and then drill down into a specific state for example? As for example when I try to do that (in my case for Australia) I still get the rest of the Australia shown just blacked out when I want to do Victoria only. I'll upload the figure so you can see what I mean. This pic also shows how I would like "AUD" to be on the line below Mental health scripts for example..

Thanks so much and sorry if I'm just misspecifying something and/or doing a terrible job reading the help file!
Karinna

**Comment by asjadnaqvi** [comment]
Dear Karinna,

Thank you for appreciating the package! Answers below:

1) You can certainly zoom into any region. If you are using a polygon overlay, you need to use the select option to zoom into the polygon e.g.:

```
bimap share_hisp share_afam using usa_county_shp_clean if STATEFP==36, cut(pctile) palette(census)  ///
		 note("Data from the US Census Bureau.", size(small)) ///	
		 texty("Share of Hispanics") textx("Share of`=char(10)'African Americans") texts(3.2) textlabs(3) values percent ///
		 ocolor(black) osize(0.03)  ///
		 polygon(data("usa_state_shp_clean") select(keep if _ID==26) ocolor(black) osize(0.2) legenda(on) leglabel(State boundaries))  ///
		 showleg legenda(off) legend(pos(7) size(5)) legstyle(2) 
```

See the `select` option in `polygon()`, that also reduced the polygon to just the state of New York. One just needs to be aware of the correct IDs.

2) Labels over two lines: Since the labels are actually marker labels, a cheap trick is to use the `=char(10)' option to add a break to the line space. In order to use this, please update the package from GitHub. It fixes some redundant label conflicts and bugs in the backend.

**Comment by asjadnaqvi** [comment]
Here is the map the above code produces:

![bimap14](https://user-images.githubusercontent.com/38498046/201656005-4ba86a18-9401-442a-8160-73ecb8e9467b.png)

**Comment by ksaxby** [comment]
Thanks so much Asjad - I really appreciate your speedy and helpful response :D this is amazing!!

I tried using the `=char(10)' which worked to put the label one level down but then unfortunately it overlaps with the y axis labels (not a problem with the xaxis as it simply goes below) and is left justified. But thanks though this was good to learn about I didn't know how to do that :)

I managed to get it working based on your advice but have a related follow-up regarding the cut offs. So when I manage to get the zoomed in version of say Victoria, I would like to apply the same tertiles so that it can be readily compared to what's presented in the overall national figure. For example in the main national figure I use pctile method to cut and then when I try to use the same cuts that were generated in the national figure, it doesn't give me the same upper bound? Possibly as that combination of expenditure/tertiles doesn't exist in the state only (in my case) expenditure patterns? I've attached some pics of NSW using pctile method as well as VIC when I do and do not use pctile method.

![Figure1_map](https://user-images.githubusercontent.com/63274020/201799314-009b748a-7375-4ab5-a738-e1d253eb093d.png)
<img width="861" alt="Figure1_map_overall" src="https://user-images.githubusercontent.com/63274020/201799321-13fd8933-edbf-48be-8baa-e9fc7305f114.png">
![Figure1_map_vic_custom](https://user-images.githubusercontent.com/63274020/201799325-02750d0b-b104-496d-97d9-09065bb1c82b.png)

This is what I used overall to get the main national map:
bimap adax_bp_qy bp_mhs_qy using "coord.dta", ///
					cut(pctile) palette(bluered) ///
					texty("Mental health scripts (AUD)") texts(3.2) textlabs(3) ///
					textx("Mental health services (AUD)") values percent 	///
					ocolor(black)  osize(0.2) formatx(%3.0f) formaty(%3.0f)

And then this example for the specific states:
*VIC only - this gives diff pctile cuts to national figure (which makes sense, same thing happens in spmap):
bimap adax_bp_qy bp_mhs_qy using "coord.dta" if STE_NAME16=="Victoria", ///
					cut(pctile)  palette(bluered) ///
					texty("Mental health scripts `=char(10)' (AUD)") texts(3.2) textlabs(3) ///
					textx("Mental health services (AUD)") values percent 	///
					formatx(%3.0f) formaty(%3.0f) ///
					polygon(data("coord") select(keep if _ID==2)) ocolor(black)  osize(0.2)

*VIC only - trying to specify same cuts that national figure generated (but gives me lower upper cuts than national
bimap adax_bp_qy bp_mhs_qy using "coord.dta" , ///
					cut(custom) cuty(3.3 4.6) cutx(7.5 11.3)  palette(bluered) ///
					texty("Mental health scripts (AUD)") texts(3.2) textlabs(3) ///
					textx("Mental health services (AUD)") values percent 	///
					formatx(%3.0f) formaty(%3.0f) ///
					polygon(data("coord") select(keep if _ID==2)) ocolor(black)  osize(0.2)

Anyway I'm probably just doing something wrong along the way haha. Really appreciate the time and work you do on this package! I'll still use the national figure no matter what :)

**Comment by asjadnaqvi** [comment]
Those look great!

1) You can use the custom cutoff option to manually define the cuts. So all the maps are comparable.

2) You can use the label offset option to move the labels a bit far from the axes and/or reduce their size. But these might not work in all cases!

**Comment by ksaxby** [comment]
Thanks so much Asjad!
I eventually got there, I realised that not all of the 'tertile combinations' that appear nationally also appear within each state so I had to update the color palette to reflect what combos were actually in there :D
Used some of your other pages and codes to help with the color palettes too :D
Cheers,
Karinna

![image](https://user-images.githubusercontent.com/63274020/203658359-5e7b0b96-bed6-4e5e-9249-3cf9b8b46495.png)

**Comment by asjadnaqvi** [comment]
label wrapping has been added in v1.9 with the `wrap()` option.
